# Generated by Django 2.2.3 on 2019-08-25 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khu_alarm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='myuser',
            table='myUser',
        ),
    ]
