# Generated by Django 2.2.3 on 2019-09-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khu_alarm', '0002_auto_20190825_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='class_id_1',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='class_id_10',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='class_id_2',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='class_id_3',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='class_id_4',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='class_id_5',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='class_id_6',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='class_id_7',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='class_id_8',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='class_id_9',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='klas_id',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='myuser',
            name='klas_pw',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
