# Generated by Django 2.2.3 on 2019-07-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_notice',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
