# Generated by Django 2.2.3 on 2019-07-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_auto_20190714_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Khu_sw_notice',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('url', models.URLField()),
            ],
            options={
                'db_table': 'khu_sw_notice',
                'ordering': ['-id'],
            },
        ),
    ]
